export const uifAttributes = [
  'data-uif',
  'data-uif-id',
  'data-uif-role',
  'data-uif-action',
  'data-uif-target',
  'data-uif-src',
  'data-uif-method',
  'data-uif-trigger',
  'data-uif-state',
  'data-uif-bind',
  'data-uif-model',
  'data-uif-value',
  'data-uif-route',
  'data-uif-mode',
  'data-uif-options',
  'data-uif-confirm',
  'data-uif-disabled',
  'data-uif-loading',
  'data-uif-success',
  'data-uif-error',
  'data-uif-swap',
  'data-uif-cache',
  'data-uif-validate',
  'data-uif-rule',
  'data-uif-event',
  'data-uif-on',
  'data-uif-refresh',
  'data-uif-persist',
  'data-uif-density',
  'data-uif-sidebar-key',
  'data-uif-density-key',
  'data-uif-toolbar',
  'data-uif-preview',
  'data-uif-animation',
  'data-uif-duration',
  'data-uif-delay',
  'data-uif-placement',
  'data-uif-container',
  'data-uif-html',
  'data-uif-backdrop',
  'data-uif-scroll',
  'data-uif-breakpoint',
  'data-uif-class',
  'data-uif-attribute',
  'data-uif-key',
] as const;

export const uifValues = [
  'button',
  'modal',
  'drawer',
  'offcanvas',
  'dropdown',
  'tabs',
  'toast',
  'accordion',
  'alert',
  'badge',
  'breadcrumb',
  'collapse',
  'tooltip',
  'popover',
  'progress',
  'spinner',
  'skeleton',
  'pagination',
  'command-menu',
  'navbar',
  'sidebar',
  'stepper',
  'wizard',
  'file-upload',
  'combobox',
  'carousel',
  'lightbox',
  'masonry',
  'card',
  'table',
  'form',
  'editor',
  'ajax',
  'route',
  'shell',
  'nav',
  'chart',
  'animate',
  'realtime',
  'push',
  'mobile-shell',
  'desktop-shell',
  'ai-action',
  'ai-thread',
  'ai-composer',
  'agent-tool',
  'tool-approval',
  'typed-text',
  'dashboard',
  'install-prompt',
] as const;

export const uifActions = [
  'open',
  'close',
  'toggle',
  'toggle-sidebar',
  'toggle-section',
  'submit',
  'load',
  'reload',
  'delete',
  'save',
  'reset',
  'clear',
  'select',
  'activate',
  'deactivate',
  'navigate',
  'swap',
  'append',
  'prepend',
  'remove',
  'toast',
  'set-density',
  'animate',
  'add-class',
  'remove-class',
  'toggle-class',
  'set-attribute',
  'remove-attribute',
  'set-value',
  'copy',
  'scroll-to',
  'focus',
  'emit',
  'subscribe',
  'connect',
  'disconnect',
  'approve',
  'reject',
] as const;

export const uifStates = [
  'idle',
  'loading',
  'loaded',
  'error',
  'success',
  'active',
  'inactive',
  'open',
  'closed',
  'disabled',
  'selected',
  'expanded',
  'collapsed',
  'connected',
  'disconnected',
  'pending',
  'approved',
  'rejected',
] as const;

export const uifEvents = [
  'uif:before-init',
  'uif:init',
  'uif:before-destroy',
  'uif:destroy',
  'uif:error',
  'uif:runtime:mounted',
  'uif:runtime:error',
  'uif:runtime:diagnostic',
  'uif:diagnostic',
  'uif:agent:submit',
  'uif:agent:cancel',
  'uif:agent:error',
  'uif:agent:feedback',
  'uif:agent:retry',
  'uif:agent:copy',
  'uif:tool-approve',
  'uif:tool-reject',
  'uif:tool-expired',
  'uif:tool-replay-blocked',
] as const;

export interface UIFContractEntry<Name extends string = string> {
  name: Name;
  version: 3;
  status: 'stable' | 'compatibility';
}

function contractEntries<const Values extends readonly string[]>(values: Values): ReadonlyArray<UIFContractEntry<Values[number]>> {
  return Object.freeze(values.map((name) => Object.freeze({ name, version: 3 as const, status: 'stable' as const })));
}

export const uifContractRegistry = Object.freeze({
  attributes: contractEntries(uifAttributes),
  components: contractEntries(uifValues),
  actions: contractEntries(uifActions),
  states: contractEntries(uifStates),
  events: contractEntries(uifEvents),
});

export type UIFAttribute = (typeof uifAttributes)[number];
export type UIFValue = (typeof uifValues)[number];
export type UIFAction = (typeof uifActions)[number];
export type UIFState = (typeof uifStates)[number];
export type UIFEvent = (typeof uifEvents)[number];
