export const uifAttributes = [
  'data-uif',
  'data-uif-id',
  'data-uif-role',
  'data-uif-action',
  'data-uif-target',
  'data-uif-src',
  'data-uif-method',
  'data-uif-trigger',
  'data-uif-state',
  'data-uif-bind',
  'data-uif-model',
  'data-uif-value',
  'data-uif-route',
  'data-uif-mode',
  'data-uif-options',
  'data-uif-confirm',
  'data-uif-disabled',
  'data-uif-loading',
  'data-uif-success',
  'data-uif-error',
  'data-uif-swap',
  'data-uif-cache',
  'data-uif-validate',
  'data-uif-rule',
  'data-uif-event',
  'data-uif-on',
  'data-uif-refresh',
  'data-uif-persist',
  'data-uif-toolbar',
  'data-uif-preview',
  'data-uif-animation',
  'data-uif-duration',
  'data-uif-delay',
  'data-uif-placement',
  'data-uif-container',
  'data-uif-html',
  'data-uif-backdrop',
  'data-uif-scroll',
  'data-uif-breakpoint',
  'data-uif-class',
  'data-uif-attribute',
  'data-uif-key',
] as const;

export const uifValues = [
  'button',
  'modal',
  'drawer',
  'offcanvas',
  'dropdown',
  'tabs',
  'toast',
  'accordion',
  'tooltip',
  'popover',
  'table',
  'form',
  'editor',
  'ajax',
  'route',
  'shell',
  'nav',
  'chart',
  'animate',
  'realtime',
  'push',
  'mobile-shell',
  'ai-action',
  'tool-approval',
] as const;

export const uifActions = [
  'open',
  'close',
  'toggle',
  'submit',
  'load',
  'reload',
  'delete',
  'save',
  'reset',
  'clear',
  'select',
  'activate',
  'deactivate',
  'navigate',
  'swap',
  'append',
  'prepend',
  'remove',
  'toast',
  'animate',
  'add-class',
  'remove-class',
  'toggle-class',
  'set-attribute',
  'remove-attribute',
  'set-value',
  'copy',
  'scroll-to',
  'focus',
  'emit',
  'subscribe',
  'connect',
  'disconnect',
  'approve',
  'reject',
] as const;

export const uifStates = [
  'idle',
  'loading',
  'loaded',
  'error',
  'success',
  'active',
  'inactive',
  'open',
  'closed',
  'disabled',
  'selected',
  'expanded',
  'collapsed',
  'connected',
  'disconnected',
  'pending',
  'approved',
  'rejected',
] as const;

export type UIFAttribute = (typeof uifAttributes)[number];
export type UIFValue = (typeof uifValues)[number];
export type UIFAction = (typeof uifActions)[number];
export type UIFState = (typeof uifStates)[number];
